server:
  port: ${PORT}
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain
    min-response-size: 1024

spring:
  application:
    name: SOCIAL-SERVICE
  cache:
    type: redis
    redis:
      time-to-live: 3600000
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD}
      timeout: 5000ms
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  ai:
    openai:
      enabled: false
    ollama:
      enabled: false

ghost:
  shield:
    jwt-secret: ${JWT_SECRET}

user:
  catalog:
    service:
      name: ${USER_CATALOG_SERVICE_NAME}
      url: ${USER_CATALOG_SERVICE_URL}

blob:
  service:
    name: ${BLOB_SERVICE_NAME}
    url: ${BLOB_SERVICE_URL}

p2p:
  service:
    url: ${P2P_URL}